### ISSUE TITLE
VIEW EVENT INFO

### ISSUE THREAD

**Issue by tf-TW** [pace-running/pace3#3]
**As an** event attendee
when I open the homepage
**I want** to view event information
**So that** I can see the relevant info such as location, time, hygiene restrictions and organiser name

Business Context: 
Currently, when the user is visiting the homepage, not all relevant information is clearly displayed. In order to give the user a better overview, information such as: location, time, hygiene restrictions, organiser name should be displayed clearly on the starting page.

Acceptance Criteria:
**Given** that I open the homepage
**When** I view the event information
**Then** I can see relevant information such as  location, time, hygiene restriction and organiser name

**Comment by cz8s** [comment]
Information on the start page is configurable now. I just don't have all the information yet. But it will be easy to post them once we have a date and a concept.

**Comment by nvinogradova** [comment]
Now the admins can change the description of the event by themselves
