### ISSUE TITLE
VIEW NEXT STEPS - EMAIL

### ISSUE THREAD

**Issue by prodb** [pace-running/pace3#30]
As an event attendee
when I sign up for the run
I want to get feedback of the successful (provisional) registration and information about necessary remaining steps
So that I can complete my registration.

Business Context:
The user shall be notified about the successful provisional registration and instructions to complete their registration.

Acceptance Criteria:

1) Given that I am on the summary
When I click on the "Anmelden" button
Then I will receive an email with a message of successful (provisional) registration including next steps for its completion.

**Comment by ckluente** [comment]
Todo: create account that can send emails as @lauf-gegen-rechts.de

**Comment by nvinogradova** [comment]
I have received the email
