### ISSUE TITLE
VIEW IMAGES FROM PREVIOUS RUNS

### ISSUE THREAD

**Issue by tf-TW** [pace-running/pace3#4]
**As an** event attendee
**I want** to view images from the previous event
**So that** I can get visual impressions of the last events/runs

Business Context: 
Currently, there are no visual representations of the previous events to convey an impression to the user. Therefore, images from the previous events should be displayed to convey impressions of how the event was to the user.

Acceptance Criteria:
**Given** that I open the homepage
**When**  I scroll down on the page
**Then** I can view different images from the previous events

**Comment by nvinogradova** [comment]
One image from previous event was added to the main page
