### ISSUE TITLE
EDIT PARTICIPANT DATA - ADMIN

### ISSUE THREAD

**Issue by prodb** [pace-running/pace3#56]
As an event organizer
I want to be able to edit a particular record of a participant
So that I can update and correct the data if necessary.

Business Context:
Admins shall be able to edit the individual records in order to manage and update the registration information.

Acceptance Criteria:
1) **Given** that I am on the admin page
**When**  I click on "Edit" in the data entry row
**Then** I get redirected to a new edit page displaying the entered data in text.

2) **Given** that I am on the participant edit page
**When**  I click on "Edit"
**Then** each data entry is changed to an input field.

3) **Given** that I am on the participant edit page and have clicked on the "Edit" button
**When**  I click on the "Confirm" button below the form
**Then** all changes in the data are saved and the data entries return to be displayed as static text.

4) **Given** that I am on the participant edit page and have clicked on the "Edit" button
**When**  I click on the "Cancel" button below the form
**Then** all changes in the data are not saved and the data entries return to be displayed as static text.

**Comment by nvinogradova** [comment]
Ability to delete a participant?

**Comment by nvinogradova** [comment]
'Wir starten als BSV Team'  - automatically unticks the checkbox on the Edit page
Acceptance criteria 3 - when I click on the "Confirm" button below the form, I am rerouted to the Admin page and cannot observe 'the data entries return to be displayed as static text'
