### ISSUE TITLE
wrong transactions are being saved in database

### ISSUE THREAD

**Issue by lihuabao** [pace-running/pace3#62]
As an admin
when I upload a csv with faulty payments
I want to see them on a separate table
So that I can fix them.

Business Context:
sometimes users make mistakes when making banking transfers and this eeds to be fixed manually

Acceptance Criteria:
1. Given I'm on the finance page, when I upload the csv including wrong payments, then the wrong payments are saved in a separate table in db. 
2. Given I'm on the finance page, the table with wrong transactions should be there

**Comment by nvinogradova** [comment]
store only rejected transactions

**Comment by nvinogradova** [comment]
TODO:
delete transactions, eliminate duplicates (but need a timestamp) -  an option: marking as a potential duplicates
