### ISSUE TITLE
Change admin password

### ISSUE THREAD

**Issue by ckluente** [pace-running/pace3#66]
As an administrator, I want to change my password so that it is not the default anymore

Background: Our migration scripts create the initial admin account with a pre-defined password. This password is hardcoded and publickly known. 
We must have an option to change the password after initial install.

The backend should offer a page where logged in users can change their password. The form should ask for the current password and the new password

**Comment by pvince81tw** [comment]
- [x] add button to admin page: https://github.com/pace-running/pace3/commits/main
- [ ] create new page to change password with fields + code to submit to backend
- [ ] implement endpoint in backend that changes password
- [ ] feature toggles (using ".env"?)

**Comment by pvince81tw** [comment]
the feature is implemented with a set of tests and works
