### ISSUE TITLE
Toggle registration

### ISSUE THREAD

**Issue by ckluente** [pace-running/pace3#70]
As an admin, I want to be able to enable and disable the registration so that I can decide when people sign up and close the registration once enough people have singed up.

Background: For the "Stadtpark Staffellauf" the team only wants to have a limited amount of participating teams. So they want to be able to close the registration once they think enough teams have signed up.

While the registration is closed, there should only be a message saying when the registration is going to open.

Optional:
Make the message when closed configurable in the backend. So that the admins can state different reasons why the registration is closed. e.g. "Registration will open on June" or "We are full, come back next year"

**Comment by nvinogradova** [comment]
@sweetsacura this too
