### ISSUE TITLE
Configure name of the event

### ISSUE THREAD

**Issue by pvince81tw** [pace-running/pace3#72]
As an admin, I want to be able to specify the name of the event and description.

Background: The "Stadtpark Staffelmarathon" will require its own name

Currently the text "Lauf gegen Recht" is hard-coded in multiple places and it would be cumbersome for sysadmins to have to edit and recompile the code just to change the event name + description.

**Comment by pvince81tw** [comment]
depending on effort and criticality we could first go with a backend side config switch/file and in another iteration add UI pages for that

**Comment by pvince81tw** [comment]
when looking at the code we found way more things that would need to be configurable to customize the site:
- Site name
    - currently "Lauf gegen Recht"
- Logo
- Landing page image
    - currently a placeholder
- List of places where a participant might run
    - currently "in Hamburg bei der Elster vor Ort"
 - City/run stats, further occurrences of "Hamburg" hard-coded, could be replaced by "city vs other"
    - in confirmation page
    - in admin page
    - ... 
 - Bank details
    - currently hard-coded in UI and emails 
 - Impressum data / page

That's quite a lot so perhaps it might be good to split this into smaller stories

**Comment by pvince81tw** [comment]
we added a database table for themes: https://github.com/pace-running/pace3/commit/e09fbe358da9b0446826d1d427cbb948b6815ec5

next up is adding an actix handler in the backend with a route to expose all theme values to the frontend

**Comment by nvinogradova** [comment]
Logo - is the same (as the organiser is the same)

**Comment by qutax** [comment]
I moved this story to done.
However, there is a bug that needs taking care of: https://github.com/pace-running/pace3/issues/86
