### ISSUE TITLE
Option during registration: Participate in the BSV competition

### ISSUE THREAD

**Issue by ckluente** [pace-running/pace3#83]
As a participant who is also member of a BSV sports team, I want my race to show up in the BSV results.

Background: BSV (Betriebssportverband) is a collection of teams participating in multiple events. They have their own tracking of results.
The Stadtpark-Marathon will be one of these events. There will be teams that want their results to be sent to BSV for inclusion in their result list.

During registration, people should have the option (yes/no) to tell the organizers that they are members of BSV and want their results be counted in the BSV result list.

Proposed wording:
"Wir starten als Betriebssport (BSV) team"

The backend should have the option to find these teams later. Proposal: Filter the teams by this option

**Comment by niklas-mertens** [comment]
To do:

- add checkbox to registration form
- adjust backend and db for additional value 'bsvParticipant'

- adjust edit runner page to display and change new checkbox

- add column to show bsvParticipant in admin table
- add possibility to filter admin table for BSV participants

**Comment by nvinogradova** [comment]
The Column 'bsvParticipant' in Admin table is missing,
Currently, it is not possible to filter admin table for BSV participant,
Wir starten als BSV Team  - automatically unticks the checkbox on Edir Runner page
