### ISSUE TITLE
Link in confirmation email must be configurable

### ISSUE THREAD

**Issue by ckluente** [pace-running/pace3#93]
Currently, the confirmation email contains a link to the self-service page. This link is hardcoded as https://lauf-gegen-rechts.de/....
We need to make this configurable depending on the instance the mail was sent from. Similar to the sender address of the email. 
Probably via a environment variable

**Comment by qutax** [comment]
Does it have to be configurable via the admin controls like the other event settings (title, description etc.) or is the `URL_HOST` environment variable sufficient?
That variables value is already in use for the emails.

See also:
- https://github.com/pace-running/pace3/blob/main/infra-setup/base/deployment.yaml#L29-L30
- https://github.com/pace-running/pace3/blob/main/backend/src/core/service/email.rs#L196

**Comment by ckluente** [comment]
environment variable is sufficient. I wasn't aware URL_HOST is already there and can be configured. 
So this is just about making sure the variable is set correctly in our 2 environments.
