### ISSUE TITLE
Handle errors if participant registration request fails

### ISSUE THREAD

**Issue by qutax** [pace-running/pace3#95]
With the implementation of #89 we check if the t-shirt ordering functionality is enabled or not.
If the functionality is disabled, the request will fail.
However, the frontend implementation of the form submit does not catch unsuccessful requests but only logs the error in the web developer console.

As goal of this story, we should implement a way to handle 4xx & 5xx response status codes in the frontend.

This will also work for the implementation of #88 which is still to be done.

**Comment by nvinogradova** [comment]
![Screenshot 2023-06-20 at 14 18 23](https://github.com/pace-running/pace3/assets/110037839/d8067d88-a8e4-4594-9423-1c8d54856781)

**Comment by nvinogradova** [comment]
![Screenshot 2023-06-21 at 09 11 47](https://github.com/pace-running/pace3/assets/110037839/bc9f29f9-585d-4011-aced-44194ad272cb)
